package com.skillstorm.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "data_plans")
public class Plan{
	
	@Id //primary key
	@GeneratedValue(strategy = GenerationType.IDENTITY) //value is generated by database
	@Column(name="dataPlanID")
	int dataPlanID;
	
	@Column(name="numberOfDevices")
	int numberOfDevices;
	
	@Column(name="planDescription")
	String planDescription;
	
	@Column(name="costPerDevice")
	double costPerDevice;

	public int getDataPlanID() {
		return dataPlanID;
	}

	public void setDataPlanID(int dataPlanID) {
		this.dataPlanID = dataPlanID;
	}

	public int getNumberOfDevices() {
		return numberOfDevices;
	}

	public void setNumberOfDevices(int numberOfDevices) {
		this.numberOfDevices = numberOfDevices;
	}

	public String getPlanDescription() {
		return planDescription;
	}

	public void setPlanDescription(String planDescription) {
		this.planDescription = planDescription;
	}

	public double getCostPerDevice() {
		return costPerDevice;
	}

	public void setCostPerDevice(double costPerDevice) {
		this.costPerDevice = costPerDevice;
	}

	@Override
	public String toString() {
		return "Plan [dataPlanID=" + dataPlanID + ", numberOfDevices=" + numberOfDevices + ", planDescription="
				+ planDescription + ", costPerDevice=" + costPerDevice + "]";
	}
	
	
}
